# Nome da aplicação
spring.application.name=sustentabilidade

# Configuração de conexão com o PostgreSQL
# Certifique-se de que a senha está correta abaixo
spring.datasource.url=jdbc:postgresql://localhost:5432/sustentabilidade_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (Isso garante que ele não apague seus dados)
# 'update' altera as tabelas automaticamente se houver mudanças no código, mas mantém os dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
